
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MY HP
 */
public class Frame16 extends javax.swing.JFrame {

    /**
     * Creates new form Frame16
     */
    public Frame16() {
        initComponents();
          setLocation(400,80);
        getContentPane().setBackground(Color.orange);
        setSize(655, 600);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox<>();
        t2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unit Converter");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setText("Unit Converter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 390, 90);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jButton1.setText("menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 70, 92, 29);

        c1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----Select Unit-------", "Angle", "Area", "Length", "Temperature", "Time", "Volume", "Weight", " " }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(24, 161, 580, 36);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Select the type of unit you want to convert  ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(24, 121, 537, 28);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel3.setText("From :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 250, 67, 39);

        c2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Select Unit----" }));
        getContentPane().add(c2);
        c2.setBounds(120, 310, 320, 44);

        t1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(120, 240, 320, 45);

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel4.setText("To :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 420, 48, 39);

        c3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        getContentPane().add(c3);
        c3.setBounds(120, 470, 320, 44);

        t2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(120, 410, 320, 45);

        jButton3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jButton3.setText("Convert");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(500, 240, 114, 42);

        jButton4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(520, 410, 100, 42);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Frame1 f1=new Frame1();
        f1.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
           if (c1.getSelectedItem()=="Angle")
        {
            c2.removeAllItems();
            c3.removeAllItems();
         //   c2.setSelectedItem(null);
            c2.addItem("Degree");
            c2.addItem("Gradian");
            c2.addItem("Radian");
            c3.addItem("Degree");
            c3.addItem("Gradian");
            c3.addItem("Radian");
            
        }   
           else if (c1.getSelectedItem()=="Area")
                   {
                       c2.removeAllItems();
                       c3.removeAllItems();
            //           c2.setSelectedItem(null);
                     c2.addItem("Acres");
                     c2.addItem("Hectare");
                   //  c2.addItem("Square Cenimeter");
                     c2.addItem("Square Foot");
                     c2.addItem("Square Inch");
                     c2.addItem("Square Kilometer");
                     c2.addItem("Square Meter");
                     
                     c3.addItem("Acres");
                     c3.addItem("Hectare");
                   //  c3.addItem("Square Cenimeter");
                     c3.addItem("Square Foot");
                     c3.addItem("Square Inch");
                     c3.addItem("Square Kilometer");
                     c3.addItem("Square Meter");
                   }
           
            else if (c1.getSelectedItem()=="Length")
                   {
                        c2.removeAllItems();
                       c3.removeAllItems();
                     c2.addItem("Centimeter");
                     c2.addItem("Foot");
                     c2.addItem("Inch");
                     c2.addItem("Kilometer");
                     c2.addItem("Meter");
                     c2.addItem("Mile");
                     c2.addItem("Yard");
                     c3.addItem("Centimeter");
                     c3.addItem("Foot");
                     c3.addItem("Inch");
                     c3.addItem("Kilometer");
                     c3.addItem("Meter");
                     c3.addItem("Mile");
                     c3.addItem("Yard");
                     
                   }
            else if(c1.getSelectedItem()=="Temperature")
            {
                 c2.removeAllItems();
                       c3.removeAllItems();
                c2.addItem("Degrees Celsius");
                c3.addItem("Degrees Celsius");
                c2.addItem("Degrees Fahrenheit");
                c3.addItem("Degrees Fahrenheit");
                c2.addItem("Kelvin");
                c3.addItem("Kelvin");
                
            }
            else if(c1.getSelectedItem()=="Time")
            {
                 c2.removeAllItems();
                       c3.removeAllItems();
                       c2.addItem("Day");
                     c2.addItem("Hours");
                     c2.addItem("Microsecond");
                     c2.addItem("Millisecond");
                     c2.addItem("Minute");
                     c2.addItem("Second");
                     c2.addItem("Week");
                     c3.addItem("Day");
                     c3.addItem("Hours");
                     c3.addItem("Microsecond");
                     c3.addItem("Millisecond");
                     c3.addItem("Minute");
                     c3.addItem("Second");
                     c3.addItem("Week");
            }
            else if(c1.getSelectedItem()=="Volume")
            {
                 c2.removeAllItems();
                       c3.removeAllItems();
                       c2.addItem("Cubic Centimeter");
                     c2.addItem("Cubic Feet");
                     c2.addItem("Cubic Inch");
                   //  c2.addItem("Cubic Yard");
                     c2.addItem("Liter");
                      c3.addItem("Cubic Centimeter");
                     c3.addItem("Cubic Feet");
                     c3.addItem("Cubic Inch");
                    // c3.addItem("Cubic Yard");
                     c3.addItem("Liter");
            }
            else if(c1.getSelectedItem()=="Weight")
            {
                 c2.removeAllItems();
                       c3.removeAllItems();
                c2.addItem("Gram");
                c2.addItem("Killogram");
                c2.addItem("Milligram");
                c2.addItem("Pounds");
                c2.addItem("Stones");
                c2.addItem("Tonne");
                 c3.addItem("Gram");
                c3.addItem("Killogram");
                c3.addItem("Milligram");
                c3.addItem("Pounds");
                c3.addItem("Stones");
                c3.addItem("Tonne");
            }
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        
        if( c2.getSelectedItem()=="Degree"& c3.getSelectedItem()=="Degree")
        {
             try{
           double b=Double.parseDouble( t1.getText());
         
           t2.setText(b+"");
           
            }catch( Exception ee)
            {
                JOptionPane.showMessageDialog(null," Enter a valid angle  in degree");
            }
        }
        
        else if( c2.getSelectedItem()=="Degree"& c3.getSelectedItem()=="Radian")
        {
             try{
           double b=Double.parseDouble( t1.getText());
           double res= Math.toRadians(b);
           t2.setText(res+"");
           
            }catch( Exception ee)
            {
                JOptionPane.showMessageDialog(null," Enter a valid angle  in degree");
            }
        }
         else if( c2.getSelectedItem()=="Degree"& c3.getSelectedItem()=="Gradian")
        {
             try{
           double b=Double.parseDouble( t1.getText());
           double res= b*1.111;
           t2.setText(res+"");
           
            }catch( Exception ee)
            {
                JOptionPane.showMessageDialog(null," Enter a valid angle  in degree");
            }
        }
          
        else if( c2.getSelectedItem()=="Gradian"& c3.getSelectedItem()=="Degree")
        {
             try{
           double b=Double.parseDouble( t1.getText());
           double res= b*0.9;
           t2.setText(res+"");
           
            }catch( Exception ee)
            {
                JOptionPane.showMessageDialog(null," Enter a valid angle  in Gradian");
            }
        }
        else if( c2.getSelectedItem()=="Gradian" & c3.getSelectedItem()=="Radian")
        {
             try{
           double b=Double.parseDouble( t1.getText());
           double res= b*0.01571;
           t2.setText(res+"");
           
            }catch( Exception ee)
            {
                JOptionPane.showMessageDialog(null," Enter a valid angle  in Gradian");
            }
        }
                else if( c2.getSelectedItem()=="Gradian" & c3.getSelectedItem()=="Gradian")
        {
             try{
           double b=Double.parseDouble( t1.getText());
          
           t2.setText(b+"");
           
            }catch( Exception ee)
            {
                JOptionPane.showMessageDialog(null," Enter a valid angle  in Gradian");
            }
        }
        else if( c2.getSelectedItem()=="Radian"& c3.getSelectedItem()=="Degree")
        {
             try{
           double b=Double.parseDouble( t1.getText());
           double res= b*57.296;
           t2.setText(res+"");
           
            }catch( Exception ee)
            {
                JOptionPane.showMessageDialog(null," Enter a valid angle  in Radian");
            }
        }
                 else if( c2.getSelectedItem()=="Radian"& c3.getSelectedItem()=="Radian")
        {
             try{
           double b=Double.parseDouble( t1.getText());
          
           t2.setText(b+"");
           
            }catch( Exception ee)
            {
                JOptionPane.showMessageDialog(null," Enter a valid angle  in Radian");
            }
        }
        else if( c2.getSelectedItem()=="Radian"& c3.getSelectedItem()=="Gradian")
            
        {
             try{
           double b=Double.parseDouble( t1.getText());
           double res= b*63.662;
           t2.setText(res+"");
           
            }catch( Exception ee)
            {
                JOptionPane.showMessageDialog(null," Enter a valid angle  in Radian");
            }  
        }
        
        
                                           //      for Area
        if (c2.getSelectedItem()=="Acres" & c3.getSelectedItem()=="Acres")
        {
            double b=Double.parseDouble(t1.getText());
            t2.setText(b+"");
            
        }
       else if (c2.getSelectedItem()=="Acres" & c3.getSelectedItem()=="Hectare")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/2.471;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Error... ");
            }
        }
       else if (c2.getSelectedItem()=="Acres" & c3.getSelectedItem()=="Square Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b*43560;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null," Error... ");
            }
        }
       else if (c2.getSelectedItem()=="Acres" & c3.getSelectedItem()=="Square Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b*6.273e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  Error... ");
            }
        }
         else if (c2.getSelectedItem()=="Acres" & c3.getSelectedItem()=="Square Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/247.1;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  Error... ");
            }
        }
         else if (c2.getSelectedItem()=="Acres" & c3.getSelectedItem()=="Square Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b*4047;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  Error... ");
            }
        }
        
        
         else if (c2.getSelectedItem()=="Hectare" & c3.getSelectedItem()=="Acres")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b*2.471;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  Error... ");
            }
        }
        else if (c2.getSelectedItem()=="Hectare" & c3.getSelectedItem()=="Hectare")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  Error... ");
            }
        }
        else if (c2.getSelectedItem()=="Hectare" & c3.getSelectedItem()=="Square Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b*107600;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  Error... ");
            }
        }
        else if (c2.getSelectedItem()=="Hectare" & c3.getSelectedItem()=="Square Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b*1.55e+7;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null," Error...  ");
            }
        }
        else if (c2.getSelectedItem()=="Hectare" & c3.getSelectedItem()=="Square Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/100;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null, ee);
            }
        }
        else if (c2.getSelectedItem()=="Hectare" & c3.getSelectedItem()=="Square Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b*10000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null, ee);
            }
        }
        
        
        
        
        
         else if (c2.getSelectedItem()=="Square Foot" & c3.getSelectedItem()=="Acres")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/43560;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null, ee);
            }
        }
        else if (c2.getSelectedItem()=="Square Foot" & c3.getSelectedItem()=="Hectare")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/107600;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null, ee);
            }
        }
        else if (c2.getSelectedItem()=="Square Foot" & c3.getSelectedItem()=="Square Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,ee);
            }
        }
        else if (c2.getSelectedItem()=="Square Foot" & c3.getSelectedItem()=="Square Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b*144;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null, ee);
            }
        }
        else if (c2.getSelectedItem()=="Square Foot" & c3.getSelectedItem()=="Square Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/1.076e+7;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,  ee);
            }
        }
        else if (c2.getSelectedItem()=="Square Foot" & c3.getSelectedItem()=="Square Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/10.764;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null, ee);
            }
        }
        
        
        
        
          else if (c2.getSelectedItem()=="Square Inch" & c3.getSelectedItem()=="Acres")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/6.273e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Inch" & c3.getSelectedItem()=="Hectare")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/1.55e+7;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Inch" & c3.getSelectedItem()=="Square Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res =b/144;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Inch" & c3.getSelectedItem()=="Square Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Inch" & c3.getSelectedItem()=="Square Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/1.55e+9;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Inch" & c3.getSelectedItem()=="Square Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/1550;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
          else if (c2.getSelectedItem()=="Square Kilometer" & c3.getSelectedItem()=="Acres")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b*247.1;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Kilometer" & c3.getSelectedItem()=="Hectare")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*100;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Kilometer" & c3.getSelectedItem()=="Square Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res =b/1.076e+7;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Kilometer" & c3.getSelectedItem()=="Square Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res =b*1.55e+9;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Kilometer" & c3.getSelectedItem()=="Square Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Kilometer" & c3.getSelectedItem()=="Square Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/1e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
         else if (c2.getSelectedItem()=="Square Meter" & c3.getSelectedItem()=="Acres")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res= b/4047;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Meter" & c3.getSelectedItem()=="Hectare")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/10000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Meter" & c3.getSelectedItem()=="Square Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res =b*10.764;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Meter" & c3.getSelectedItem()=="Square Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res =b*1550;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Meter" & c3.getSelectedItem()=="Square Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          double res=b/1e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Square Meter" & c3.getSelectedItem()=="Square Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
                              //     For Length
        
         else if (c2.getSelectedItem()=="Centimeter" & c3.getSelectedItem()=="Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Centimeter" & c3.getSelectedItem()=="Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/30.48;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Centimeter" & c3.getSelectedItem()=="Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/2.54;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Centimeter" & c3.getSelectedItem()=="Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/100000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Centimeter" & c3.getSelectedItem()=="Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/100;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Centimeter" & c3.getSelectedItem()=="Mile")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/160900;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Centimeter" & c3.getSelectedItem()=="Yard")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/91.44;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
      
            else if  (c2.getSelectedItem()=="Foot" & c3.getSelectedItem()=="Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*30.48;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Foot" & c3.getSelectedItem()=="Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
     
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Foot" & c3.getSelectedItem()=="Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*12;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Foot" & c3.getSelectedItem()=="Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/3281;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Foot" & c3.getSelectedItem()=="Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/3.281;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Foot" & c3.getSelectedItem()=="Mile")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/5280;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Foot" & c3.getSelectedItem()=="Yard")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/3;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
            else if  (c2.getSelectedItem()=="Inch" & c3.getSelectedItem()=="Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*2.54;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Inch" & c3.getSelectedItem()=="Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
         double res= b/12;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Inch" & c3.getSelectedItem()=="Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Inch" & c3.getSelectedItem()=="Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/39370;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Inch" & c3.getSelectedItem()=="Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/39.37;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Inch" & c3.getSelectedItem()=="Mile")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/63360;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Inch" & c3.getSelectedItem()=="Yard")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/36;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        
            else if  (c2.getSelectedItem()=="Kilometer" & c3.getSelectedItem()=="Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*100000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Kilometer" & c3.getSelectedItem()=="Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
         double res= b*3281;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Kilometer" & c3.getSelectedItem()=="Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*39370;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Kilometer" & c3.getSelectedItem()=="Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Kilometer" & c3.getSelectedItem()=="Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Kilometer" & c3.getSelectedItem()=="Mile")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/1.609;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Kilometer" & c3.getSelectedItem()=="Yard")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1094;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        
            else if  (c2.getSelectedItem()=="Meter" & c3.getSelectedItem()=="Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*100;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Meter" & c3.getSelectedItem()=="Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
         double res= b*3.281;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Meter" & c3.getSelectedItem()=="Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*39.37;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Meter" & c3.getSelectedItem()=="Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Meter" & c3.getSelectedItem()=="Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           // double res=b*1000;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Meter" & c3.getSelectedItem()=="Mile")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/1609;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Meter" & c3.getSelectedItem()=="Yard")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1.094;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
            else if  (c2.getSelectedItem()=="Mile" & c3.getSelectedItem()=="Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*160900;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Mile" & c3.getSelectedItem()=="Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
         double res= b*5280;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Mile" & c3.getSelectedItem()=="Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*63360;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Mile" & c3.getSelectedItem()=="Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1.609;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Mile" & c3.getSelectedItem()=="Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1609;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Mile" & c3.getSelectedItem()=="Mile")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           // double res=b/1609;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Mile" & c3.getSelectedItem()=="Yard")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1760;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
            else if  (c2.getSelectedItem()=="Yard" & c3.getSelectedItem()=="Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*91.44;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Yard" & c3.getSelectedItem()=="Foot")
        {
            try{
            double b=Double.parseDouble(t1.getText());
         double res= b*3;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Yard" & c3.getSelectedItem()=="Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*36;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Yard" & c3.getSelectedItem()=="Kilometer")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/1094;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Yard" & c3.getSelectedItem()=="Meter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/1.094;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Yard" & c3.getSelectedItem()=="Mile")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/1760;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Yard" & c3.getSelectedItem()=="Yard")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          //  double res=b*1760;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
            
                              // Temperature
       
         
         
         else if (c2.getSelectedItem()=="Degrees Celsius" & c3.getSelectedItem()=="Degrees Celsius")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          // double res=b/1760;
            t2.setText(b+"degrees celsius");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Degrees Celsius" & c3.getSelectedItem()=="Degrees Fahrenheit")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=(b*1.8)+32;
            t2.setText(res+"degrees fahrenheit");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Degrees Celsius" & c3.getSelectedItem()=="Kelvin")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b+273.15;
            t2.setText(res+"K");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
         else if (c2.getSelectedItem()=="Degrees Fahrenheit" & c3.getSelectedItem()=="Degrees Celsius")
        {
            try{
            double b=Double.parseDouble(t1.getText());
             double res=(b-32)*0.555;
            t2.setText(res+"degrees celsius");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Degrees Fahrenheit" & c3.getSelectedItem()=="Degrees Fahrenheit")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           // double res=(b*1.8)+32;
            t2.setText(b+"degrees fahrenheit");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Degrees Fahrenheit" & c3.getSelectedItem()=="Kelvin")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=((b-32)*0.555)+273.15;
            t2.setText(res+"K");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
          else if (c2.getSelectedItem()=="Kelvin" & c3.getSelectedItem()=="Degrees Celsius")
        {
            try{
            double b=Double.parseDouble(t1.getText());
             double res=b-273.15;
            t2.setText(res+"degrees celsius");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Kelvin" & c3.getSelectedItem()=="Degrees Fahrenheit")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=((b-273.15)*1.8)+32;
            t2.setText(res+"degrees fahrenheit");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Kelvin" & c3.getSelectedItem()=="Kelvin")
        {
            try{
            double b=Double.parseDouble(t1.getText());
         //   double res=((b-32)*0.555)+273.15;
            t2.setText(b+"K");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        // Time
        
           else if (c2.getSelectedItem()=="Day" & c3.getSelectedItem()=="Day")
        {
            try{
            double b=Double.parseDouble(t1.getText());
         //   double res=((b-32)*0.555)+273.15;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Day" & c3.getSelectedItem()=="Hours")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*24;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Day" & c3.getSelectedItem()=="Microsecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*8.64e+10;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Day" & c3.getSelectedItem()=="Millisecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*8.64e+7;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Day" & c3.getSelectedItem()=="Minute")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1440;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Day" & c3.getSelectedItem()=="Second")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*86400;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Day" & c3.getSelectedItem()=="'Week")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/7;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        else if (c2.getSelectedItem()=="Hours" & c3.getSelectedItem()=="Day")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/24;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Hours" & c3.getSelectedItem()=="Hours")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          //  double res=b*24;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Hours" & c3.getSelectedItem()=="Microsecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*3.6e+9;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Hours" & c3.getSelectedItem()=="Millisecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*3.6e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Hours" & c3.getSelectedItem()=="Minute")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*60;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Hours" & c3.getSelectedItem()=="Second")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*3600;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Hours" & c3.getSelectedItem()=="'Week")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/168;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        
        
        else if (c2.getSelectedItem()=="Microsecond" & c3.getSelectedItem()=="Day")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/8.64e+10;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Microsecond" & c3.getSelectedItem()=="Hours")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/3.6e+9;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Microsecond" & c3.getSelectedItem()=="Microsecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           // double res=b*3.6e+9;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Microsecond" & c3.getSelectedItem()=="Millisecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Microsecond" & c3.getSelectedItem()=="Minute")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/6e+7;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Microsecond" & c3.getSelectedItem()=="Second")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/1e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Microsecond" & c3.getSelectedItem()=="'Week")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/6.048e+11;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        
        
        else if (c2.getSelectedItem()=="Millisecond" & c3.getSelectedItem()=="Day")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/8.64e+7;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Millisecond" & c3.getSelectedItem()=="Hours")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/3.6e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Millisecond" & c3.getSelectedItem()=="Microsecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Millisecond" & c3.getSelectedItem()=="Millisecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          //  double res=b/1000;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Millisecond" & c3.getSelectedItem()=="Minute")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/60000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Millisecond" & c3.getSelectedItem()=="Second")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Millisecond" & c3.getSelectedItem()=="'Week")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/6.048e+8;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        
        
        
        else if (c2.getSelectedItem()=="Minute" & c3.getSelectedItem()=="Day")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/1440;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Minute" & c3.getSelectedItem()=="Hours")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/60;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Minute" & c3.getSelectedItem()=="Microsecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*6e+7;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Minute" & c3.getSelectedItem()=="Millisecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*60000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Minute" & c3.getSelectedItem()=="Minute")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          //  double res=b/60000;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Minute" & c3.getSelectedItem()=="Second")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*60;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Minute" & c3.getSelectedItem()=="'Week")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/10080;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        
        else if (c2.getSelectedItem()=="Second" & c3.getSelectedItem()=="Day")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/86400;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Second" & c3.getSelectedItem()=="Hours")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/3600;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Second" & c3.getSelectedItem()=="Microsecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Second" & c3.getSelectedItem()=="Millisecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Second" & c3.getSelectedItem()=="Minute")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/60;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Second" & c3.getSelectedItem()=="Second")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          //  double res=b*60;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Second" & c3.getSelectedItem()=="'Week")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/604800;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        
        
        
        
        else if (c2.getSelectedItem()=="Week" & c3.getSelectedItem()=="Day")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*7;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Week" & c3.getSelectedItem()=="Hours")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*168;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Week" & c3.getSelectedItem()=="Microsecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*6.048e+11;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Week" & c3.getSelectedItem()=="Millisecond")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*6.048e+8;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          else if (c2.getSelectedItem()=="Week" & c3.getSelectedItem()=="Minute")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*10080;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Week" & c3.getSelectedItem()=="Second")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*604800;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Week" & c3.getSelectedItem()=="'Week")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           // double res=b/604800;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        //     volume
        
        
         else if (c2.getSelectedItem()=="Cubic Centimeter" & c3.getSelectedItem()=="Cubic Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           // double res=b/604800;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Cubic Centimeter" & c3.getSelectedItem()=="Cubic Feet")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/28320;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
            else if (c2.getSelectedItem()=="Cubic Centimeter" & c3.getSelectedItem()=="Cubic Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/16.387;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          
            else if (c2.getSelectedItem()=="Cubic Centimeter" & c3.getSelectedItem()=="Liter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        
        
        else if (c2.getSelectedItem()=="Cubic Feet" & c3.getSelectedItem()=="Cubic Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*28320;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Cubic Feet" & c3.getSelectedItem()=="Cubic Feet")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           // double res=b/28320;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
            else if (c2.getSelectedItem()=="Cubic Feet" & c3.getSelectedItem()=="Cubic Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1728;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          
            else if (c2.getSelectedItem()=="Cubic Feet" & c3.getSelectedItem()=="Liter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*28.317;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        else if (c2.getSelectedItem()=="Cubic Inch" & c3.getSelectedItem()=="Cubic Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*16.387;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Cubic Inch" & c3.getSelectedItem()=="Cubic Feet")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/1728;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
            else if (c2.getSelectedItem()=="Cubic Inch" & c3.getSelectedItem()=="Cubic Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
         //   double res=b*1728;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          
            else if (c2.getSelectedItem()=="Cubic Inch" & c3.getSelectedItem()=="Liter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/61.024;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        else if (c2.getSelectedItem()=="Liter" & c3.getSelectedItem()=="Cubic Centimeter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
           else if (c2.getSelectedItem()=="Liter" & c3.getSelectedItem()=="Cubic Feet")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/28.317;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
            else if (c2.getSelectedItem()=="Liter" & c3.getSelectedItem()=="Cubic Inch")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*61.024;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
          
            else if (c2.getSelectedItem()=="Liter" & c3.getSelectedItem()=="Liter")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          //  double res=b/61.024;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        //  Weight
        
            else if (c2.getSelectedItem()=="Gram" & c3.getSelectedItem()=="Gram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          //  double res=b/61.024;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Gram" & c3.getSelectedItem()=="Killogram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Gram" & c3.getSelectedItem()=="Milligram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Gram" & c3.getSelectedItem()=="Pounds")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/453.6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Gram" & c3.getSelectedItem()=="Stones")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/6350;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Gram" & c3.getSelectedItem()=="Tonne")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/1e+6;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        else if (c2.getSelectedItem()=="Killogram" & c3.getSelectedItem()=="Gram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Killogram" & c3.getSelectedItem()=="Killogram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
        //   double res=b/1000;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Killogram" & c3.getSelectedItem()=="Milligram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*1e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Killogram" & c3.getSelectedItem()=="Pounds")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*2.205;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Killogram" & c3.getSelectedItem()=="Stones")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/6.35;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Killogram" & c3.getSelectedItem()=="Tonne")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/1000;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
         else if (c2.getSelectedItem()=="Milligram" & c3.getSelectedItem()=="Gram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Milligram" & c3.getSelectedItem()=="Killogram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/1e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Milligram" & c3.getSelectedItem()=="Milligram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          // double res=b*1e+6;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Milligram" & c3.getSelectedItem()=="Pounds")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/453600;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Milligram" & c3.getSelectedItem()=="Stones")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/6.35e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Milligram" & c3.getSelectedItem()=="Tonne")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/1e+9;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        
         else if (c2.getSelectedItem()=="Pounds" & c3.getSelectedItem()=="Gram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*453.6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Pounds" & c3.getSelectedItem()=="Killogram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b/2.205;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Pounds" & c3.getSelectedItem()=="Milligram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*453600;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Pounds" & c3.getSelectedItem()=="Pounds")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          // double res=b/453600;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Pounds" & c3.getSelectedItem()=="Stones")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/14;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Pounds" & c3.getSelectedItem()=="Tonne")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/2205;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
        
        
        
         else if (c2.getSelectedItem()=="Stones" & c3.getSelectedItem()=="Gram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*6350;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Stones" & c3.getSelectedItem()=="Killogram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*6.35;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Stones" & c3.getSelectedItem()=="Milligram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*6.35e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Stones" & c3.getSelectedItem()=="Pounds")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*14;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Stones" & c3.getSelectedItem()=="Stones")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           //double res=b/14;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Stones" & c3.getSelectedItem()=="Tonne")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b/157.5;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        
        
        
        
        
         else if (c2.getSelectedItem()=="Tonne" & c3.getSelectedItem()=="Gram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*1e+6;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
        else if (c2.getSelectedItem()=="Tonne" & c3.getSelectedItem()=="Killogram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
            double res=b*1000;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Tonne" & c3.getSelectedItem()=="Milligram")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*1e+9;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Tonne" & c3.getSelectedItem()=="Pounds")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*2205;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Tonne" & c3.getSelectedItem()=="Stones")
        {
            try{
            double b=Double.parseDouble(t1.getText());
           double res=b*157.5;
            t2.setText(res+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
         else if (c2.getSelectedItem()=="Tonne" & c3.getSelectedItem()=="Tonne")
        {
            try{
            double b=Double.parseDouble(t1.getText());
          // double res=b/157.5;
            t2.setText(b+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null,"  ee");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");
         c1.setSelectedIndex(0);
        c2.setSelectedIndex(-1);
        c3.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame16().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
