
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MY HP
 */
public class Frame5 extends javax.swing.JFrame {

    /**
     * Creates new form Frame5
     */
    public Frame5() {
        initComponents();
        setLocation(400,80);
        getContentPane().setBackground(Color.pink);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        c2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base Converter");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\java programing\\base1.png")); // NOI18N
        jLabel2.setText(" Base Converter");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel3.setText("     To:");

        t2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        c2.setFont(new java.awt.Font("Segoe UI", 0, 18));
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal", "Binary", "Hexa", "Octal" }));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel4.setText("From :");

        c1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal", "Binary", "Hexa", "Octal" }));

        t1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String l=(String) c1.getSelectedItem();
        String k=(String ) c2.getSelectedItem();

        if(c1.getSelectedItem()=="Decimal" & c2.getSelectedItem()=="Binary")
        {
            try{
            String z=t1.getText();
            int x=Integer.parseInt(z);
            String z1=Integer.toBinaryString(x);
            t2.setText(z1);
            }catch (Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter a Decimal number only " );
            }
        }
        else if(c1.getSelectedItem()=="Decimal"&c2.getSelectedItem()=="Hexa")
        {
            try{
            String z=t1.getText();
            int x=Integer.parseInt(z);
            String z1=Integer.toHexString(x);
            t2.setText(z1+"");
            }catch (Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter a Decimal number only " );
            }

        }
        else if(c1.getSelectedItem()=="Decimal"&c2.getSelectedItem()=="Octal")
        {
            try{
            String z=t1.getText();
            int x=Integer.parseInt(z);
            String z1=Integer.toOctalString(x);
            t2.setText(z1+"");
             }catch (Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter a Decimal number only " );
            }
        }
        else if(c1.getSelectedItem()=="Decimal"&c2.getSelectedItem()=="Decimal")
        {
            try{
            String f=t1.getText();
            t2.setText(f);
            }catch (Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter a Decimal number only " );
            }
        }
            
            
            
            
            
        else if(c1.getSelectedItem()=="Binary"&c2.getSelectedItem()=="Decimal")
        {
            try{ String z=t1.getText();
                int x=Integer.parseInt(z,2);

                t2.setText(x+"");
            }catch (Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter Only Binary Number " );
            }
        }
        else if(c1.getSelectedItem()=="Binary"&c2.getSelectedItem()=="Binary")
        {
          try{
                String str=t1.getText();
                t2.setText(str);
                
                }catch (Exception ee)
           {
                JOptionPane.showMessageDialog(null, "Enter a Binary number only " );
            }
            }
        
        else if(c1.getSelectedItem()=="Binary"&c2.getSelectedItem()=="Hexa")
        {
            try{
                String x=t1.getText();
                int y=Integer.parseInt(x,2);
                String z1=Integer.toHexString(y);

                t2.setText(z1+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter a valid Binary number" );
            }
        }
        else if (c1.getSelectedItem()=="Binary"&c2.getSelectedItem()=="Octal")
        {try{
            String num=t1.getText();
            int y=Integer.parseInt(num,2);
            String num2=Integer.toOctalString(y);
            t2.setText(num2+"");
        }catch(Exception ee)
        {
            JOptionPane.showMessageDialog(null, "Enter a valid Binary Number");

        }
        }
        

        // COPY

        else if(c1.getSelectedItem()=="Hexa"&c2.getSelectedItem()=="Decimal")
        {
            try{
                String z=t1.getText();
                int x=Integer.parseInt(z,16);

                t2.setText(x+"");
            }catch (Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter  HexaDecimal  " );
            }
        }
        else if(c1.getSelectedItem()=="Hexa"&c2.getSelectedItem()=="Hexa")
        {
            try{
                String z=t1.getText();
                t2.setText(z);
            }catch (Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter  HexaDecimal  " );
            }
        }
        
        else if(c1.getSelectedItem()=="Hexa"&c2.getSelectedItem()=="Binary")
        {
            try{
                String x=t1.getText();
                int y=Integer.parseInt(x,16);
                String z1=Integer.toBinaryString(y);

                t2.setText(z1+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter a valid hexadecimal" );
            }
        }
        else if (c1.getSelectedItem()=="Hexa"&c2.getSelectedItem()=="Octal")
        {try{
            String num=t1.getText();
            int y=Integer.parseInt(num,16);
            String num2=Integer.toOctalString(y);
            t2.setText(num2+"");
        }catch(Exception ee)
        {
            JOptionPane.showMessageDialog(null, "Enter a valid Binary Number");

        }
        }
        // octal series

        else if(c1.getSelectedItem()=="Octal"&c2.getSelectedItem()=="Decimal")
        {
            try{
                String z=t1.getText();
                int x=Integer.parseInt(z,8);

                t2.setText(x+"");
            }catch (Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter  a valid octal number  " );
            }
        }
        else if(c1.getSelectedItem()=="Octal"&c2.getSelectedItem()=="Binary")
        {
            try{
                String x=t1.getText();
                int y=Integer.parseInt(x,8);
                String z1=Integer.toBinaryString(y);

                t2.setText(z1+"");
            }catch(Exception ee)
            {
                JOptionPane.showMessageDialog(null, "Enter a valid octal number" );
            }
        }
        else if (c1.getSelectedItem()=="Octal"&c2.getSelectedItem()=="Hexa")
        {try{
            String num=t1.getText();
            int y=Integer.parseInt(num,8);
            String num2=Integer.toHexString(y);
            t2.setText(num2+"");
        }catch(Exception ee)
        {
            JOptionPane.showMessageDialog(null, "Enter a valid Octal Number");

        }
        }
        else if (c1.getSelectedItem()=="Octal"&c2.getSelectedItem()=="Octal")
        {try{
            String num=t1.getText();
           
            t2.setText(num);
        }catch(Exception ee)
        {
            JOptionPane.showMessageDialog(null, "Enter a valid Octal Number");

        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");
        c1.setSelectedIndex(0);
        c2.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Frame1 f1=new Frame1();
        f1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
