
import java.awt.Color;
import static java.lang.Math.exp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MY HP
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
        setLocation(400,80);
        getContentPane().setBackground(Color.pink);
        setSize(626,550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        bequal = new javax.swing.JButton();
        bminus = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        bplus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arithmetic Calculator");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java programing\\arthmetic.jpg")); // NOI18N
        jLabel1.setText(" Arithmetic Calculator");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 15, 458, 100);

        t1.setEditable(false);
        t1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(t1);
        t1.setBounds(44, 144, 514, 63);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(499, 92, 90, 34);

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 0));
        jButton2.setText("/");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(193, 239, 98, 43);

        b6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(310, 350, 88, 37);

        b0.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        getContentPane().add(b0);
        b0.setBounds(90, 460, 110, 37);

        b5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(190, 350, 88, 37);

        b9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(310, 300, 88, 37);

        b.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b.setText(".");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(250, 460, 110, 37);

        b2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(190, 400, 88, 37);

        b8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(190, 300, 88, 37);

        b3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(310, 400, 88, 37);

        b7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(70, 300, 88, 37);

        jButton12.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 153, 0));
        jButton12.setText("*");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(309, 239, 98, 43);

        b4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(70, 350, 88, 37);

        b1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(70, 400, 88, 37);

        bequal.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        bequal.setForeground(new java.awt.Color(51, 153, 0));
        bequal.setText("=");
        bequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bequalActionPerformed(evt);
            }
        });
        getContentPane().add(bequal);
        bequal.setBounds(440, 420, 98, 43);

        bminus.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        bminus.setForeground(new java.awt.Color(51, 153, 0));
        bminus.setText("-");
        bminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bminusActionPerformed(evt);
            }
        });
        getContentPane().add(bminus);
        bminus.setBounds(440, 300, 98, 43);

        jButton14.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(51, 153, 0));
        jButton14.setText("%");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(67, 239, 98, 43);

        jButton16.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton16.setText("Clear");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(443, 239, 98, 43);

        bplus.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        bplus.setForeground(new java.awt.Color(51, 153, 0));
        bplus.setText("+");
        bplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bplusActionPerformed(evt);
            }
        });
        getContentPane().add(bplus);
        bplus.setBounds(443, 362, 98, 43);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Frame1 f=new Frame1();
          f.setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
            String s=t1.getText();
          t1.setText(s+evt.getActionCommand());
        
    }//GEN-LAST:event_b3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_b0ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_bActionPerformed

    private void bplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bplusActionPerformed
        // TODO add your handling code here:
      /*  String exp;
        if(!(exp.equals("")))
        {
            char cop= exp.charAt (exp.length()-1);
            if(!(cop=='+'|| cop=='-' || cop=='*' || cop=='/') )
            {
                exp+="+";
                t1.setText(exp);
            }
        }  */
         String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
      
    }//GEN-LAST:event_bplusActionPerformed

    private void bminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bminusActionPerformed
        // TODO add your handling code here:
           String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_bminusActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
           String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
           String s=t1.getText();
        t1.setText(s+evt.getActionCommand());
    }//GEN-LAST:event_jButton14ActionPerformed

    private void bequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bequalActionPerformed
        // TODO add your handling code here:
          String s1=t1.getText();
        int p=s1.indexOf("+");
        if (p>0)
        {
           String s2=s1.substring(0,p);
           String s3=s1.substring(p+1);
           double a=Double.parseDouble(s2);
           double b=Double.parseDouble(s3);
           double c=a+b;
          
           t1.setText(c +"");
           
        }
         p=s1.indexOf("-");
        if (p>0)
        {
           String s2=s1.substring(0,p);
           String s3=s1.substring(p+1);
           double a=Double.parseDouble(s2);
           double b=Double.parseDouble(s3);
           double c=a-b;
           t1.setText(c +"");
        }
         p=s1.indexOf("/");
        if (p>0)
        {
           String s2=s1.substring(0,p);
           String s3=s1.substring(p+1);
           double a=Double.parseDouble(s2);
           double b=Double.parseDouble(s3);
           double c=a/b;
           t1.setText(c +"");
        }
         p=s1.indexOf("*");
        if (p>0)
        {
           String s2=s1.substring(0,p);
           String s3=s1.substring(p+1);
           double a=Double.parseDouble(s2);
           double b=Double.parseDouble(s3);
           double c=a*b;
           t1.setText(c +"");
        }
    }//GEN-LAST:event_bequalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bequal;
    private javax.swing.JButton bminus;
    private javax.swing.JButton bplus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
