
import java.awt.Color;
import java.util.Arrays;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MY HP
 */
public class Frame6 extends javax.swing.JFrame {

    /**
     * Creates new form Frame6
     */
    public Frame6() {
        initComponents();
        setLocation(420,120);
        getContentPane().setBackground(Color.orange);
       setSize(824, 657);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l1 = new javax.swing.JTextField();
        l2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        l3 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        t5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Statistic Calculator");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 35)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java programing\\mean.jpg")); // NOI18N
        jLabel1.setText(" Statistic Calculator");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 480, 98);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 130, 80, 28);

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Ascending Order :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 460, 144, 44);

        jLabel7.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Descending Order :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 540, 150, 44);

        l1.setEditable(false);
        l1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(130, 256, 204, 44);

        l2.setEditable(false);
        l2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        getContentPane().add(l2);
        l2.setBounds(130, 315, 204, 44);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel2.setText("Enter all numbers separated by comma , Eg- 7,11,21,14");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 120, 565, 52);

        l3.setEditable(false);
        l3.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(130, 380, 204, 44);

        t1.setFont(new java.awt.Font("HP Simplified Jpan", 0, 20)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t1);
        t1.setBounds(10, 180, 610, 48);

        t4.setEditable(false);
        t4.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        getContentPane().add(t4);
        t4.setBounds(170, 460, 580, 44);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Calculate");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(640, 180, 148, 53);

        t5.setEditable(false);
        t5.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        getContentPane().add(t5);
        t5.setBounds(180, 540, 577, 44);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(710, 120, 85, 43);

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Mean :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 256, 66, 44);

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Median :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 315, 76, 44);

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Mode :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 380, 67, 44);

        jLabel8.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Standard Deviation :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 370, 160, 44);

        t6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(t6);
        t6.setBounds(560, 370, 200, 44);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String [] s= t1.getText().trim().split(",");

        // to parse a string [] to integer array
        int [] s1 = new int[s.length];
        for(int i=0;i<s1.length;i++)
        {
            s1[i]=Integer.parseInt(s[i]);
        }
        // for mean
        int sum=0;
        for(int item : s1)
        {
            sum += item;

        }
        double  s2=s1.length;

        double rslt=sum/s2;
        l1.setText(rslt+"");
        
        // standard deviation
        double sum1=0;
        double sd=0;
        int len=s1.length;
         for(double num: s1)
         {
             sum1 +=num;
         }
           double mean=sum1/len;
        for(double num:s1)
        {
            sd=sd+Math.pow(num-mean, 2);
        }
       double rs= Math.sqrt((sd/len));
        t6.setText(rs+"");
        
        
        
        // for median
        Arrays.sort(s1);
        int   b=s1.length/2;
        if(s1.length% 2 != 0)
        {

            l2.setText(s1[b]+"");
        }   else
        {
            int res = (s1[b]+s1[b-1]) /2;
            l2.setText( res +"");
        }
        // for mode

        int maxnumber =0;
        int maxappearence =0;
        for(int i=0;i<s1.length;i++)
        {
            int count=0;
            for(int j=0;j<s1.length;j++)
            {
                if ( s1[i] == s1[j] )
                count ++;

            }
            if(count > maxappearence)
            {
                maxnumber = s1[i];
                maxappearence =count;
            }
        }

        l3.setText(maxnumber +"");

        // sorting
        Arrays.sort(s1);

        String str= Arrays.toString(s1);
        t4.setText(str);

        int yo;
        for(int i=0;i<s1.length;i++)
        {
            for (int j=i+1; j<s1.length;j++)
            {
                if (s1[i]<s1[j])
                {
                    yo=s1[i];
                    s1[i]=s1[j];
                    s1[j]=yo;

                }
            }
        }
        String z= Arrays.toString(s1);
        t5.setText(z);

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        l1.setText("");
        l2.setText("");
        l3.setText("");
        t4.setText("");
        t5.setText("");
          t6.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Frame1 f1=new Frame1();
        f1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField l1;
    private javax.swing.JTextField l2;
    private javax.swing.JTextField l3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
